# Funding Configuration for Addocu
# Support the development of this free, open-source tool

github: [jrodeiro5]
ko_fi: addocu
custom: ["https://addocu.com/sponsor", "https://buymeacoffee.com/addocu"]
